---
title: Imperium Production
timezone: Europe/Paris
collections:
  artistes:
    title: Artistes
    output: true
  menus:
    title: Menus
    output: true
  mixtapes:
    title: Mixtapes
    output: true
  photos:
    title: Photos
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
slider-titre: Imperium prod arrive bientot...
slider-sous-titre: Production de Musique, Videos
coming-soon-background-image: "/uploads/6211631cc5efb244d31e204f6ffc91d7_accueil-studio_1500-999.jpeg"
facebook-lien: https://www.facebook.com/
twitter-lien: https://www.twitter.com/
instagram-lien: https://www.instagram.com/
footer-text: texte de bas de page
phone: 44449553935
email: test@email.com
